package com.matteoveroni.wordsremember.factories;

/**
 * @author Matteo Veroni
 */

public enum PresenterFactoryName {
    MAIN_MENU_PRESENTER_FACTORY,
    LOGIN_PRESENTER_FACTORY,
    SETTINGS_PRESENTER_FACTORY,
    USER_PROFILE_PRESENTER,
    USER_PROFILE_EDITOR_PRESENTER,
    ADD_TRANSLATION_PRESENTER_FACTORY,
    EDIT_TRANSLATION_PRESENTER_FACTORY,
    EDIT_VOCABLE_PRESENTER_FACTORY,
    MANAGE_VOCABLE_PRESENTER_FACTORY,
    QUIZ_GAME_PRESENTER_FACTORY,
    QUIZ_GAME_REPORT_PRESENTER_FACTORY
}
